# Why we can't trust numerical computation?

## Quick Recap

In [1]:
# This is a matrix
import numpy as np
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])
print(mat1)


[[1 2]
 [3 4]]


In [3]:
# This is how we do arithmetic on two matrices.
print("Adding two Matrices:\n {} \n".format(mat1 + mat2))
print("Adding two Matrices:\n {} \n".format(mat1 - mat2))
print("Multiplying two matrices?:\n {} \n".format(mat1 * mat2))

Adding two Matrices:
 [[ 6  8]
 [10 12]] 

Adding two Matrices:
 [[-4 -4]
 [-4 -4]] 

Multiplying two matrices?:
 [[ 5 12]
 [21 32]] 



In [4]:
# Multiplying two matrices
np.matmul(mat1, mat2)

array([[19, 22],
       [43, 50]])

In [5]:
# and since it's a quick recap
np.matmul(mat1, mat2) == np.matmul(mat2, mat1)

array([[False, False],
       [False, False]])

## Matrix multiplication is not commutative

 "Why, you might just as well say that **I see what I eat** is the same thing as **I eat what I see** " - Lewis Caroll (Alice in the wonderland)

## Identity matrix

$$A \times A^{-1} = I$$
Where $ A^{-1} $ is the inverse of Matrix $A$

In [6]:
print(np.matmul(mat2,np.linalg.inv(mat2)))

[[1. 0.]
 [0. 1.]]


# Easy, right?

*psst, remember those physics problems from high school?*

<img src="air_resistance.jpeg" width="750">

The "air resistance" of matrices generally comes up in computation because of trucation in floating points. (especially in matrices because of their non-commutative property)

It is important to keep this in the back of your head (somewhere) - will come in handy one day, trust me ;)

There's an entire branch of mathematics, Numerical Analysis, that deals with this specifically.

Is it even important? Should I be worried?

- Yes?

<img src="anexamplewouldbegreat.jpeg" width=350 >

In [1]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

NameError: name 'np' is not defined

In [8]:
np.matmul(np.linalg.pinv(A), A)

array([[ 0.83333333,  0.33333333, -0.16666667],
       [ 0.33333333,  0.33333333,  0.33333333],
       [-0.16666667,  0.33333333,  0.83333333]])

## Let's try to do the inverse operation with these two matrices



$$A = \begin{bmatrix} 0.0001 & 1 \\ 1 & 1 \end{bmatrix} \quad\quad  \text{and} \quad\quad B = \begin{bmatrix} 1 & 1 \\ 1 & 1.0001 \end{bmatrix}$$

In [9]:
# PS: numpy is row-major
A = np.array([[0.0001, 1], [1,1]])
B = np.array([[1, 1], [1,1.0001]])
np.set_printoptions(precision=4, suppress=True) # damn those unredable scientific notations
# only 39 digits of pi are used to calculate the circumference of the universe, us, mere mortals, are good with 4 digits

In [10]:
print(A)

[[0.0001 1.    ]
 [1.     1.    ]]


In [11]:
print(B)

[[1.     1.    ]
 [1.     1.0001]]


## Calculating the inverse

In [16]:
A_inverse = np.matmul(np.linalg.inv(A), A)
print(A_inverse)

[[1. 0.]
 [0. 1.]]


## Calculating the inverse

In [17]:
B_inverse = np.matmul(np.linalg.inv(B), B)
print(B_inverse)

[[1.0000e+00 8.5265e-17]
 [0.0000e+00 1.0000e+00]]


Bear in mind, numpy has a precision of 15 bits.

In [19]:
print(np.finfo(np.double).precision)

15


Huh, Don't cite exceptions as examples

Consider again, this system

$$Ax = B$$ <br>
$$A = \begin{bmatrix} 10&7&8&7\\7&5&6&5\\8&6&10&9\\7&5&9&10 \end{bmatrix} B = \begin{bmatrix} 32\\23\\33\\31 \end{bmatrix}$$
therefore,
$$x = A^{-1} B$$ <br>

In [2]:
A = np.array([[10,7,8,7],[7,5,6,5],[8,6,10,9],[7,5,9,10]])
B = np.array([32,23,33,31])

In [3]:
print(A)

[[10  7  8  7]
 [ 7  5  6  5]
 [ 8  6 10  9]
 [ 7  5  9 10]]


In [4]:
B

array([32, 23, 33, 31])

In [5]:
A_inverse = np.linalg.inv(A)

In [6]:
np.matmul(A_inverse, B)

array([1., 1., 1., 1.])

All good? Now lets shake things up

Now assume that there's a very small change associated with A, could be anything.

$$ A + \begin{bmatrix} 0&0&0.1&0.2\\0.08&0.04&0&0\\0&-0.02&-0.11&0\\-0.01&-0.01&0&-0.02 \end{bmatrix}$$

In [7]:
delta_A = A + np.array([[0,0,0.1,0.2],[0.08,0.04,0,0],[0,-0.02,-0.11,0],[-0.01,-0.01,0,-0.02]])
delta_A_inverse = np.linalg.inv(delta_A)

In [8]:
delta_A

array([[10.  ,  7.  ,  8.1 ,  7.2 ],
       [ 7.08,  5.04,  6.  ,  5.  ],
       [ 8.  ,  5.98,  9.89,  9.  ],
       [ 6.99,  4.99,  9.  ,  9.98]])

In [9]:
A

array([[10,  7,  8,  7],
       [ 7,  5,  6,  5],
       [ 8,  6, 10,  9],
       [ 7,  5,  9, 10]])

In [10]:
np.matmul(delta_A_inverse, B)

array([-81., 137., -34.,  22.])

<img src="woah.gif">

The product of the n eigenvalues of A is the same as the determinant of A

In [3]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.float64)

In [8]:
np.linalg.eig(A)

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [16]:
1.61168440e+01 * -1.11684397e+00 * -1.30367773e-15

2.3466199188015338e-14

In [9]:
np.linalg.det(A)

0.0

## What's your point? $10^{-15}$ is so small that it is considered as 0, right? RIGHT? RIGHT?

In [18]:
B = np.array([[1,2,1], [2,1,2], [1,1,3]])
very_small_B = (10**-17)*B

In [19]:
very_small_B

array([[1.e-17, 2.e-17, 1.e-17],
       [2.e-17, 1.e-17, 2.e-17],
       [1.e-17, 1.e-17, 3.e-17]])

In [20]:
np.linalg.eig(very_small_B)

(array([ 4.73205081e-17, -1.00000000e-17,  1.26794919e-17]),
 array([[ 4.91061909e-01,  7.07106781e-01, -6.74173847e-01],
        [ 6.01064312e-01, -7.07106781e-01, -4.00575614e-01],
        [ 6.30539368e-01, -2.76714839e-17,  6.20506891e-01]]))

In [21]:
np.linalg.det(very_small_B)

-6.000000000000021e-51

In [23]:
np.linalg.inv(very_small_B)

array([[-1.66666667e+16,  8.33333333e+16, -5.00000000e+16],
       [ 6.66666667e+16, -3.33333333e+16,  0.00000000e+00],
       [-1.66666667e+16, -1.66666667e+16,  5.00000000e+16]])

In [24]:
np.matmul(np.linalg.inv(very_small_B), very_small_B)

array([[ 1.00000000e+00,  1.06273393e-16,  1.73812772e-16],
       [ 5.29865856e-17,  1.00000000e+00,  5.29865856e-17],
       [ 4.74890956e-18, -1.06273393e-16,  1.00000000e+00]])

0 is ... relative?

Okay, I'm sold. What's happening here?

<video src="GoodMatrix.mp4" width = 500px controls>

<video src="ill_conditioned_matrix.mp4" width = 500px controls>

Cue in: <h3> Condition number </h3>

![img](whatisaconditionnumber.jpg)

In a nutshell, condition number will tell you how good/reliable would be the results that come out of a matrix

The smaller condition number, the better it is.

Large condition numbers will make the calculations unreliable. Anything above or at ($10^{13}$) will give absolute grabage results

Tl;dr
Small Condition number -> GOOD <br/>
Large Condition number -> BAD! 

In [31]:
np.linalg.cond([[10,7,8,7],[7,5,6,5],[8,6,10,9],[7,5,9,10]]) # Matrix A

2984.0927016757555

In [32]:
np.linalg.cond([[1,2,1], [2,1,2], [1,1,3]])  # Matrix B

5.474178435810782

Mathematically, if the condition number is less than $\infty$, the matrix is invertible. Numerically, there are roundomff errors which occur. A high condition number means that the matrix is almost non-invertible

It's not just inverses. The entire calculation can go haywire if your matrix is ill-conditioned

In [89]:
mat2 = [[-2, -3],[-2, -3.000001]]

In [90]:
np.matmul(mat2, [1,1])

array([-5.      , -5.000001])

In [91]:
np.linalg.det(mat2)

2.000000000279557e-06

In [92]:
np.matmul(np.linalg.inv(mat2), mat2)

array([[ 1.00000000e+00, -2.32830573e-10],
       [ 0.00000000e+00,  1.00000000e+00]])

In [95]:
delta_mat2 = mat2 + np.array([[0.001, 0.02], [0.0, -0.12]])

In [96]:
np.matmul(delta_mat2, [1,1])

array([-4.979   , -5.120001])

- Should I be worried? No, numpy handles it to a good extent. Matlab does it better. 
- What can I do about it? 

Human intervention cannot be replaced. If you're getting some arbitary values. Do a raincheck with condition numbers.

It's not you, it's ~~me~~ matrices. Definitely the matrices

*FIN*