In [39]:
import numpy as np

In [40]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.float64)

In [41]:
print(A)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [42]:
np.linalg.det(A)

0.0

In [43]:
np.matmul(np.linalg.inv(A), A)

LinAlgError: Singular matrix

The product of the n eigenvalues of A is the same as the determinant of A

In [44]:
B = np.array([[1,2,1], [2,1,2], [1,1,3]])
b_mul = (10**-17)*B

In [45]:
np.linalg.eig(b_mul)

(array([ 4.73205081e-17, -1.00000000e-17,  1.26794919e-17]),
 array([[ 4.91061909e-01,  7.07106781e-01, -6.74173847e-01],
        [ 6.01064312e-01, -7.07106781e-01, -4.00575614e-01],
        [ 6.30539368e-01, -2.76714839e-17,  6.20506891e-01]]))

In [46]:
np.linalg.det(b_mul)

-6.000000000000021e-51

In [47]:
A = np.array([[0.0001, 1], [1,1]])
B = np.array([[1, 1], [1,1.0001]])
np.set_printoptions(precision=4, suppress=False)

In [48]:
np.matmul(np.linalg.inv(A), A)

array([[1., 0.],
       [0., 1.]])

In [49]:
np.matmul(np.linalg.inv(B), B)

array([[1.0000e+00, 8.5265e-17],
       [0.0000e+00, 1.0000e+00]])

In [50]:
A = np.array([[10,7,8,7],[7,5,6,5],[8,6,10,9],[7,5,9,10]])
B = np.array([32,23,33,31])

In [51]:
x = np.matmul(np.linalg.inv(A),B)

In [52]:
delta_A = A + np.array([[0,0,0.1,0.2],[0.08,0.04,0,0],[0,-0.02,-0.11,0],[-0.01,-0.01,0,-0.02]])
print(delta_A)
delta_A_inverse = np.linalg.inv(delta_A)

[[10.    7.    8.1   7.2 ]
 [ 7.08  5.04  6.    5.  ]
 [ 8.    5.98  9.89  9.  ]
 [ 6.99  4.99  9.    9.98]]


In [54]:
np.matmul(delta_A, B)

array([971.5 , 695.48, 998.91, 944.83])


[7/4 1/4]
[3/4 5/4]

In [15]:
mat = np.array([[7./4.,3./4. ],[1./4.,5./4.]])

In [16]:
print(mat)

[[1.75 0.75]
 [0.25 1.25]]


In [17]:
np.linalg.eig(mat)

(array([2., 1.]), array([[ 0.9486833 , -0.70710678],
        [ 0.31622777,  0.70710678]]))

In [18]:
np.linalg.eig

<function numpy.linalg.eig(a)>

In [26]:
def check_eigen(ar):
    print(ar)
    print(np.linalg.eig(ar))

In [34]:
check_eigen(np.array([[1,-1],[-1,-1]]))

[[ 1 -1]
 [-1 -1]]
(array([ 1.41421356, -1.41421356]), array([[ 0.92387953,  0.38268343],
       [-0.38268343,  0.92387953]]))


In [37]:
np.sqrt(2)/1.41421356

1.0000000016780317